# Generated by Django 4.1.13 on 2024-10-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('words', models.TextField(blank=True, null=True)),
                ('full_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
